@extends('layouts.admin')
@section('title','نقش‌ها و دسترسی‌ها | مدیریت')
@section('content')
<div class="admin-top"><div><h1>نقش‌ها و دسترسی‌ها</h1><div class="muted">Spatie Permission • دسترسی مبتنی بر Role/Permission</div></div><a class="admin-btn alt" href="{{ route('admin.users.index') }}">کاربران</a></div>
@can('users.manage')<form class="admin-card admin-grid" method="post" action="{{ route('admin.roles.store') }}">@csrf<div class="admin-field"><label>نام نقش جدید</label><input class="ltr" name="name" required placeholder="sales-manager"></div><div class="admin-field"><label>دسترسی‌های اولیه</label><div class="permission-grid">@foreach($permissions as $permission)<label><input type="checkbox" name="permissions[]" value="{{ $permission->name }}"> {{ $permission->name }}</label>@endforeach</div></div><div><button class="admin-btn gold">ایجاد نقش</button></div></form>@endcan
<div class="admin-grid">@foreach($roles as $role)<section class="admin-card"><div class="admin-top" style="margin-bottom:14px"><div><h3 style="margin:0" class="ltr">{{ $role->name }}</h3><div class="muted">{{ $role->users_count }} کاربر • {{ $role->permissions->count() }} دسترسی</div></div>@if($role->name==='super-admin')<span class="badge ok">محافظت‌شده</span>@endif</div>
@if($role->name==='super-admin')<div class="muted">این نقش به تمام Permissionها دسترسی دارد و قابل حذف/محدودسازی نیست.</div>@else @can('users.manage')<form method="post" action="{{ route('admin.roles.update',$role) }}">@csrf @method('PATCH')<div class="permission-grid">@foreach($permissions as $permission)<label><input type="checkbox" name="permissions[]" value="{{ $permission->name }}" @checked($role->hasPermissionTo($permission->name))> {{ $permission->name }}</label>@endforeach</div><div class="admin-actions" style="margin-top:16px"><button class="admin-btn gold">ذخیره دسترسی‌ها</button></form><form method="post" action="{{ route('admin.roles.destroy',$role) }}" onsubmit="return confirm('نقش حذف شود؟')">@csrf @method('DELETE')<button class="admin-btn alt">حذف نقش</button></form></div>@endcan @endif
</section>@endforeach</div>
@endsection
