@extends('layouts.app')
@section('title',$project->title.' | پروژه‌های خانه فرش')
@section('meta_description',$project->excerpt ?: 'مشاهده جزئیات پروژه '.$project->title)
@section('og_type','article')
@section('og_image',$project->cover_url)
@section('content')
<article><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">PROJECT / {{ $project->year ?: now()->year }}</span><h1>{{ $project->title }}</h1></div><p>{{ $project->excerpt }}</p></div><div class="product-visual" style="min-height:auto"><img src="{{ $project->cover_url }}" alt="{{ $project->title }}" width="1400" height="900" fetchpriority="high" style="width:100%;height:auto;object-fit:cover"></div><div class="project-detail-grid" style="margin-top:32px"><div><h2>درباره پروژه</h2><div style="line-height:2;color:#4e4a43">{!! nl2br(e($project->content ?: $project->excerpt)) !!}</div></div><aside><div class="spec-list"><div><span>موقعیت</span><b>{{ $project->location ?: '—' }}</b></div><div><span>سال اجرا</span><b>{{ $project->year ?: '—' }}</b></div></div></aside></div>@if($project->getMedia('gallery')->isNotEmpty())<div class="collection-grid" style="margin-top:48px">@foreach($project->getMedia('gallery') as $media)<figure class="collection-card"><img src="{{ $media->getUrl() }}" alt="{{ $project->title }} - تصویر {{ $loop->iteration }}" loading="lazy" width="700" height="520"></figure>@endforeach</div>@endif</div></section></article>
@push('structured-data')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'CreativeWork','name'=>$project->title,'description'=>$project->excerpt,'image'=>$project->cover_url,'locationCreated'=>$project->location,'dateCreated'=>$project->year?($project->year.'-01-01'):null,'url'=>route('projects.show',$project)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>@endpush
@endsection
