@extends('layouts.admin')
@section('title','داشبورد مدیریت | خانه فرش')
@section('toolbar_title','نمای کلی فروشگاه')
@section('content')
<div class="admin-top"><div><span class="admin-page-kicker">COMMERCE OVERVIEW</span><h1>سلام، {{ strtok(auth()->user()?->name ?? 'مدیر',' ') }}</h1><div class="muted">فروش، سفارش، موجودی و عملیات فروشگاه در یک نگاه.</div></div><div class="admin-actions">@can('products.manage')<a class="admin-btn alt" href="{{ route('admin.products.create') }}">＋ محصول جدید</a>@endcan<a class="admin-btn gold" href="{{ route('admin.orders.index') }}">مدیریت سفارش‌ها</a></div></div>
<div class="metric-grid"><article class="metric"><span class="metric-icon">↗</span><small>فروش کل پرداخت‌شده</small><b>{{ number_format($metrics['revenue']) }}</b><span class="metric-note">تومان · این ماه {{ number_format($metrics['monthRevenue']) }}</span></article><article class="metric"><span class="metric-icon">▤</span><small>کل سفارش‌ها</small><b>{{ number_format($metrics['orders']) }}</b><span class="metric-note">{{ number_format($metrics['paidOrders']) }} سفارش پرداخت‌شده</span></article><article class="metric"><span class="metric-icon">◎</span><small>مشتریان یکتا</small><b>{{ number_format($metrics['customers']) }}</b><span class="metric-note">بر اساس شماره تماس سفارش‌ها</span></article><article class="metric"><span class="metric-icon">◇</span><small>کاتالوگ</small><b>{{ number_format($metrics['products']) }}</b><span class="metric-note">{{ number_format($metrics['lowStock']) }} محصول با موجودی کم</span></article></div>
<div class="dashboard-grid"><section class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">14 DAY REVENUE</span><h2>ریتم فروش دو هفته اخیر</h2><p>فقط تراکنش‌های پرداخت‌شده محاسبه شده‌اند.</p></div><b>{{ number_format($salesSeries->sum('revenue')) }} <small>تومان</small></b></div><div class="sales-chart" aria-label="نمودار فروش ۱۴ روز اخیر">@foreach($salesSeries as $point)<div class="sales-bar-wrap" title="{{ $point['label'] }} — {{ number_format($point['revenue']) }} تومان"><div class="sales-bar" style="height:{{ max(4,round(($point['revenue']/$maxRevenue)*100)) }}%"></div><small>{{ $point['label'] }}</small></div>@endforeach</div><div class="pipeline">@foreach(['pending'=>'در انتظار','processing'=>'پردازش','inventory_review'=>'بررسی موجودی','packed'=>'بسته‌بندی','shipped'=>'ارسال','completed'=>'تکمیل'] as $key=>$label)<span>{{ $label }} <b>{{ number_format((int)($pipeline[$key]??0)) }}</b></span>@endforeach</div></section><aside class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">ATTENTION</span><h2>نیازمند اقدام</h2><p>موجودی‌های کم و کالاهای رو به اتمام.</p></div><a class="admin-btn alt" href="{{ route('admin.products.index') }}">کاتالوگ</a></div><div class="split-list">@forelse($lowStockProducts as $product)<div class="split-row"><div><b>{{ $product->name }}</b><small class="ltr">{{ $product->sku }}</small></div><span class="badge {{ $product->stock===0?'danger':'warn' }}">{{ $product->stock }} عدد</span></div>@empty<div class="muted">موجودی بحرانی وجود ندارد.</div>@endforelse</div></aside></div>
<div class="dashboard-grid" style="margin-top:18px"><section class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">RECENT ORDERS</span><h2>آخرین سفارش‌ها</h2></div><a class="admin-btn alt" href="{{ route('admin.orders.index') }}">همه سفارش‌ها</a></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>شماره سفارش</th><th>مشتری</th><th>مبلغ</th><th>پرداخت</th><th>وضعیت</th><th></th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td><b class="ltr">{{ $order->order_number }}</b><div class="muted">{{ $order->created_at?->format('Y/m/d H:i') }}</div></td><td>{{ $order->customer_name }}<div class="muted ltr">{{ $order->phone }}</div></td><td>{{ number_format($order->total) }} تومان</td><td><span class="badge {{ $order->payment_status==='paid'?'ok':'warn' }}">{{ $order->payment_status==='paid'?'پرداخت‌شده':'در انتظار' }}</span></td><td>{{ ['pending'=>'در انتظار','processing'=>'پردازش','inventory_review'=>'بررسی موجودی','packed'=>'بسته‌بندی','shipped'=>'ارسال شده','completed'=>'تکمیل','cancelled'=>'لغو'][$order->status]??$order->status }}</td><td><a class="admin-btn alt" href="{{ route('admin.orders.show',$order) }}">جزئیات</a></td></tr>@empty<tr><td colspan="6">سفارشی وجود ندارد.</td></tr>@endforelse</tbody></table></div></section><aside class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">TOP PRODUCTS</span><h2>محصولات پرفروش</h2></div></div><div class="split-list">@forelse($topProducts as $product)<div class="split-row"><div><b>{{ $product->product_name }}</b><small>{{ number_format($product->revenue) }} تومان</small></div><span class="badge ok">{{ number_format($product->sold) }} فروش</span></div>@empty<div class="muted">داده‌ای برای نمایش وجود ندارد.</div>@endforelse</div></aside></div>
@endsection
