@extends('layouts.admin')
@section('title','گزارش‌ها | مدیریت')
@section('content')
<div class="admin-top"><div><h1>گزارش فروش</h1><div class="muted">۳۰ روز اخیر، محصولات پرفروش و هشدار موجودی</div></div></div>
@php($revenue=$salesByDay->sum('revenue')) @php($orders=$salesByDay->sum('orders'))
<div class="admin-grid admin-grid-3"><div class="admin-card"><div class="muted">فروش ۳۰ روز</div><h2>{{ number_format($revenue) }}</h2><div class="muted">تومان</div></div><div class="admin-card"><div class="muted">سفارش پرداخت‌شده</div><h2>{{ number_format($orders) }}</h2></div><div class="admin-card"><div class="muted">میانگین سبد</div><h2>{{ number_format($orders?intdiv((int)$revenue,(int)$orders):0) }}</h2><div class="muted">تومان</div></div></div>
<div class="admin-grid admin-grid-2" style="margin-top:18px"><section class="admin-card"><h3>روند روزانه</h3><div style="overflow:auto"><table class="admin-table"><thead><tr><th>تاریخ</th><th>سفارش</th><th>فروش</th></tr></thead><tbody>@forelse($salesByDay as $row)<tr><td class="ltr">{{ $row->day }}</td><td>{{ $row->orders }}</td><td>{{ number_format($row->revenue) }} تومان</td></tr>@empty<tr><td colspan="3">در این بازه فروش پرداخت‌شده‌ای ثبت نشده است.</td></tr>@endforelse</tbody></table></div></section><section class="admin-card"><h3>پرفروش‌ترین محصولات</h3><div style="overflow:auto"><table class="admin-table"><thead><tr><th>محصول</th><th>تعداد</th><th>فروش</th></tr></thead><tbody>@forelse($topProducts as $row)<tr><td>{{ $row->product_name }}</td><td>{{ $row->qty }}</td><td>{{ number_format($row->revenue) }}</td></tr>@empty<tr><td colspan="3">داده‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div></section></div>
<section class="admin-card" style="margin-top:18px"><div class="admin-top"><div><h3>موجودی پایین</h3><div class="muted">محصولات با موجودی ۳ یا کمتر</div></div><a class="admin-btn alt" href="{{ route('admin.products.index') }}">مدیریت محصولات</a></div><table class="admin-table"><thead><tr><th>محصول</th><th>SKU</th><th>موجودی</th><th></th></tr></thead><tbody>@forelse($lowStock as $product)<tr><td>{{ $product->name }}</td><td class="ltr">{{ $product->sku }}</td><td><span class="badge warn">{{ $product->stock }}</span></td><td><a class="admin-btn alt" href="{{ route('admin.products.edit',$product) }}">ویرایش</a></td></tr>@empty<tr><td colspan="4">موجودی بحرانی ندارید.</td></tr>@endforelse</tbody></table></section>
@endsection
