@extends('layouts.admin')
@section('title','تنظیمات فروشگاه | مدیریت')
@section('toolbar_title','تنظیمات سیستم')
@section('content')
<div class="admin-top"><div><span class="admin-page-kicker">STORE CONFIGURATION</span><h1>تنظیمات فروشگاه</h1><div class="muted">هویت برند، SEO، ارسال، درگاه پرداخت و سرویس پیامک.</div></div></div><form class="admin-grid" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
<section class="admin-card"><div class="settings-section-title"><div><h2>هویت و ارتباط</h2><p>اطلاعاتی که در صفحات عمومی استفاده می‌شوند.</p></div><span class="badge ok">Public</span></div><div class="admin-grid admin-grid-2"><div class="admin-field"><label>نام فروشگاه</label><input name="store_name" required value="{{ old('store_name',$settings['store_name']??'خانه فرش') }}"></div><div class="admin-field"><label>شعار برند</label><input name="store_tagline" value="{{ old('store_tagline',$settings['store_tagline']??'') }}"></div><div class="admin-field"><label>تلفن</label><input class="ltr" name="store_phone" value="{{ old('store_phone',$settings['store_phone']??'') }}"></div><div class="admin-field"><label>Instagram URL</label><input class="ltr" type="url" name="instagram_url" value="{{ old('instagram_url',$settings['instagram_url']??'') }}"></div><div class="admin-field" style="grid-column:1/-1"><label>آدرس</label><textarea rows="3" name="store_address">{{ old('store_address',$settings['store_address']??'') }}</textarea></div><div class="admin-field"><label>هزینه ثابت ارسال (تومان)</label><input type="number" min="0" name="shipping_flat" value="{{ old('shipping_flat',$settings['shipping_flat']??0) }}"></div></div></section>
<section class="admin-card"><div class="settings-section-title"><div><h2>SEO پیش‌فرض</h2><p>Fallback متادیتا برای صفحاتی که عنوان اختصاصی ندارند.</p></div><span class="badge">Search</span></div><div class="admin-grid admin-grid-2"><div class="admin-field"><label>SEO Title</label><input name="seo_default_title" maxlength="190" value="{{ old('seo_default_title',$settings['seo_default_title']??'') }}"></div><div class="admin-field"><label>Meta Description</label><textarea rows="4" maxlength="320" name="seo_default_description">{{ old('seo_default_description',$settings['seo_default_description']??'') }}</textarea></div></div></section>
<div class="admin-grid admin-grid-2"><section class="admin-card"><div class="settings-section-title"><div><h2>زرین‌پال</h2><p>Merchant ID رمزنگاری‌شده نگهداری می‌شود.</p></div><span class="badge {{ ($status['zarinpal_configured']??false)?'ok':'warn' }}">{{ ($status['zarinpal_configured']??false)?'Configured':'Missing' }}</span></div><div class="secure-note">در repository عمومی Merchant ID واقعی commit نمی‌شود. مقدار جدید فقط در Encrypted Settings یا ENV ذخیره شود.</div><div class="admin-field" style="margin-top:16px"><label>Merchant ID جدید</label><input class="ltr" name="zarinpal_merchant_id" autocomplete="new-password" placeholder="خالی = حفظ مقدار فعلی"></div><label class="toggle-row"><span><b>Sandbox mode</b><small class="muted">برای تست بدون تراکنش واقعی.</small></span><input type="checkbox" name="zarinpal_sandbox" value="1" @checked(old('zarinpal_sandbox',(bool)($settings['zarinpal_sandbox']??true)))></label></section><section class="admin-card"><div class="settings-section-title"><div><h2>کاوه‌نگار</h2><p>API Key رمزنگاری شده و دوباره نمایش داده نمی‌شود.</p></div><span class="badge {{ ($status['kavenegar_configured']??false)?'ok':'warn' }}">{{ ($status['kavenegar_configured']??false)?'Configured':'Missing' }}</span></div><div class="admin-field"><label>API Key جدید</label><input class="ltr" name="kavenegar_api_key" autocomplete="new-password" placeholder="خالی = حفظ مقدار فعلی"></div><div class="admin-grid admin-grid-2" style="margin-top:14px"><div class="admin-field"><label>Sender</label><input class="ltr" name="kavenegar_sender" value="{{ old('kavenegar_sender',$settings['kavenegar_sender']??'') }}"></div><div class="admin-field"><label>Verify template</label><input class="ltr" name="kavenegar_verify_template" value="{{ old('kavenegar_verify_template',$settings['kavenegar_verify_template']??'') }}"></div></div><label class="toggle-row"><span><b>Sandbox / Suppress SMS</b><small class="muted">در این حالت هیچ درخواست خارجی ارسال نمی‌شود.</small></span><input type="checkbox" name="kavenegar_sandbox" value="1" @checked(old('kavenegar_sandbox',(bool)($settings['kavenegar_sandbox']??true)))></label></section></div>
@can('settings.manage')<div><button class="admin-btn gold" type="submit">ذخیره تنظیمات</button></div>@endcan</form>
@endsection
