@extends('layouts.admin')
@section('title','تنظیمات فروشگاه | مدیریت')
@section('content')
<div class="admin-top"><div><h1>تنظیمات فروشگاه</h1><div class="muted">برند، تماس، ارسال، SEO، زرین‌پال و کاوه‌نگار</div></div></div>
<form class="admin-grid" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
<div class="admin-card admin-grid admin-grid-2"><div class="admin-field"><label>نام فروشگاه</label><input name="store_name" required value="{{ old('store_name',$settings['store_name']??'خانه فرش') }}"></div><div class="admin-field"><label>شعار برند</label><input name="store_tagline" value="{{ old('store_tagline',$settings['store_tagline']??'') }}"></div><div class="admin-field"><label>تلفن</label><input class="ltr" name="store_phone" value="{{ old('store_phone',$settings['store_phone']??'') }}"></div><div class="admin-field"><label>Instagram URL</label><input class="ltr" type="url" name="instagram_url" value="{{ old('instagram_url',$settings['instagram_url']??'') }}"></div><div class="admin-field" style="grid-column:1/-1"><label>آدرس</label><textarea rows="3" name="store_address">{{ old('store_address',$settings['store_address']??'') }}</textarea></div><div class="admin-field"><label>هزینه ثابت ارسال (تومان)</label><input type="number" min="0" name="shipping_flat" value="{{ old('shipping_flat',$settings['shipping_flat']??0) }}"></div></div>
<div class="admin-card admin-grid admin-grid-2"><div class="admin-field"><label>SEO Title پیش‌فرض</label><input name="seo_default_title" maxlength="190" value="{{ old('seo_default_title',$settings['seo_default_title']??'') }}"></div><div class="admin-field"><label>SEO Description پیش‌فرض</label><textarea rows="4" maxlength="320" name="seo_default_description">{{ old('seo_default_description',$settings['seo_default_description']??'') }}</textarea></div></div>
<div class="admin-card"><div class="admin-top"><div><h3 style="margin:0">زرین‌پال</h3><div class="muted">کلید در دیتابیس به‌صورت رمزنگاری‌شده ذخیره می‌شود.</div></div><span class="badge {{ ($status['zarinpal_configured']??false)?'ok':'warn' }}">{{ ($status['zarinpal_configured']??false)?'تنظیم شده':'تنظیم نشده' }}</span></div><div class="admin-grid admin-grid-2"><div class="admin-field"><label>Merchant ID جدید</label><input class="ltr" name="zarinpal_merchant_id" autocomplete="new-password" placeholder="خالی بگذارید تا مقدار فعلی حفظ شود"></div><label style="align-self:end"><input type="checkbox" name="zarinpal_sandbox" value="1" @checked(old('zarinpal_sandbox',(bool)($settings['zarinpal_sandbox']??true)))> حالت Sandbox</label></div></div>
<div class="admin-card"><div class="admin-top"><div><h3 style="margin:0">کاوه‌نگار</h3><div class="muted">API Key نمایش داده نمی‌شود و رمزنگاری‌شده ذخیره می‌شود.</div></div><span class="badge {{ ($status['kavenegar_configured']??false)?'ok':'warn' }}">{{ ($status['kavenegar_configured']??false)?'تنظیم شده':'تنظیم نشده' }}</span></div><div class="admin-grid admin-grid-3"><div class="admin-field"><label>API Key جدید</label><input class="ltr" name="kavenegar_api_key" autocomplete="new-password" placeholder="خالی = حفظ مقدار فعلی"></div><div class="admin-field"><label>شماره ارسال‌کننده</label><input class="ltr" name="kavenegar_sender" value="{{ old('kavenegar_sender',$settings['kavenegar_sender']??'') }}"></div><div class="admin-field"><label>Template احراز</label><input class="ltr" name="kavenegar_verify_template" value="{{ old('kavenegar_verify_template',$settings['kavenegar_verify_template']??'') }}"></div></div></div>
@can('settings.manage')<div><button class="admin-btn gold">ذخیره همه تنظیمات</button></div>@endcan</form>
@endsection
