@extends('layouts.admin')
@section('title','سفارش '.$order->order_number)
@section('toolbar_title','جزئیات سفارش')
@section('content')
@php($statusLabels=['pending'=>'در انتظار','processing'=>'در حال پردازش','inventory_review'=>'بررسی موجودی','packed'=>'بسته‌بندی','shipped'=>'ارسال شده','completed'=>'تکمیل','cancelled'=>'لغو','refunded'=>'بازپرداخت'])
<div class="admin-top"><div><span class="admin-page-kicker">ORDER DETAIL</span><h1>سفارش <span class="ltr">{{ $order->order_number }}</span></h1><div class="muted">{{ $order->customer_name }} · <span class="ltr">{{ $order->phone }}</span> · {{ $order->created_at?->format('Y/m/d H:i') }}</div></div><div class="admin-actions">@if($order->payment_status==='paid' && $order->invoice_number)<a class="admin-btn alt" target="_blank" href="{{ route('orders.invoice',['order'=>$order->public_token]) }}">چاپ فاکتور ↗</a>@endif<a class="admin-btn" href="{{ route('admin.orders.index') }}">بازگشت</a></div></div>
<div class="metric-grid"><div class="metric"><small>مبلغ نهایی</small><b>{{ number_format($order->total) }}</b><span class="metric-note">تومان</span></div><div class="metric"><small>پرداخت</small><b style="font-size:20px">{{ $order->payment_status==='paid'?'پرداخت‌شده':'در انتظار' }}</b><span class="metric-note ltr">Ref: {{ $order->payment_ref_id ?: '—' }}</span></div><div class="metric"><small>وضعیت سفارش</small><b style="font-size:20px">{{ $statusLabels[$order->status]??$order->status }}</b><span class="metric-note">آخرین بروزرسانی {{ $order->updated_at?->format('Y/m/d H:i') }}</span></div><div class="metric"><small>شماره فاکتور</small><b class="ltr" style="font-size:17px">{{ $order->invoice_number ?: '—' }}</b><span class="metric-note">{{ $order->payment_gateway }}</span></div></div>
<div class="dashboard-grid"><section class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">ORDER ITEMS</span><h2>اقلام فاکتور</h2></div></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>محصول</th><th>SKU</th><th>تعداد</th><th>قیمت واحد</th><th>جمع</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><b>{{ $item->product_name }}</b></td><td class="ltr">{{ $item->sku }}</td><td>{{ $item->quantity }}</td><td>{{ number_format($item->unit_price) }}</td><td><b>{{ number_format($item->total_price) }}</b></td></tr>@endforeach</tbody></table></div><div class="split-list" style="margin-top:18px"><div class="split-row"><span>جمع کالا</span><b>{{ number_format($order->subtotal) }} تومان</b></div><div class="split-row"><span>تخفیف {{ $order->coupon_code?'('.$order->coupon_code.')':'' }}</span><b>{{ number_format($order->discount_amount) }} تومان</b></div><div class="split-row"><span>ارسال</span><b>{{ number_format($order->shipping_amount) }} تومان</b></div><div class="split-row"><span>مبلغ نهایی</span><b style="font-size:18px">{{ number_format($order->total) }} تومان</b></div></div></section><aside class="admin-panel"><div class="panel-head"><div><span class="admin-page-kicker">FULFILLMENT</span><h2>مدیریت وضعیت</h2></div></div><form class="admin-grid" method="post" action="{{ route('admin.orders.update',$order) }}">@csrf @method('PATCH')<div class="admin-field"><label>وضعیت سفارش</label><select name="status">@foreach($statusLabels as $key=>$label)<option value="{{ $key }}" @selected($order->status===$key)>{{ $label }}</option>@endforeach</select></div><div class="admin-field"><label>یادداشت تغییر وضعیت</label><input name="status_note" placeholder="مثلاً تحویل پست شد یا با مشتری هماهنگ شد"></div><div class="admin-field"><label>یادداشت داخلی سفارش</label><textarea rows="5" name="notes">{{ $order->notes }}</textarea></div>@can('orders.manage')<button class="admin-btn gold">ثبت تغییر وضعیت</button>@endcan</form><div class="secure-note" style="margin-top:18px"><b>آدرس ارسال</b><br>{{ collect($order->shipping_address)->filter()->implode('، ') }}</div></aside></div>
<section class="admin-panel" style="margin-top:18px"><div class="panel-head"><div><span class="admin-page-kicker">AUDIT TRAIL</span><h2>تاریخچه سفارش</h2><p>هر تغییر وضعیت با زمان و کاربر ثبت می‌شود.</p></div></div><div class="timeline">@forelse($order->statusHistories as $history)<div class="timeline-item"><span class="timeline-dot">✓</span><div><b>{{ $statusLabels[$history->from_status]??($history->from_status?:'شروع') }} ← {{ $statusLabels[$history->to_status]??$history->to_status }}</b><small>{{ $history->created_at?->format('Y/m/d H:i') }} @if($history->actor) · {{ $history->actor->name }} @endif</small>@if($history->note)<div class="muted">{{ $history->note }}</div>@endif</div></div>@empty<div class="muted">تاریخچه‌ای ثبت نشده است.</div>@endforelse</div></section>
@endsection
