<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>@yield('title', $settings['seo_default_title'] ?? $settings['store_name'] ?? 'خانه فرش')</title>
<meta name="description" content="@yield('meta_description', $settings['seo_default_description'] ?? 'فروشگاه تخصصی فرش، قالی، تابلو فرش، فرشینه و موکت با انتخاب حرفه‌ای و خرید امن آنلاین.')">
<meta name="theme-color" content="#ffffff"><meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="@yield('canonical', url()->current())">
<meta property="og:type" content="@yield('og_type', 'website')"><meta property="og:title" content="@yield('title', $settings['store_name'] ?? 'خانه فرش')"><meta property="og:description" content="@yield('meta_description', $settings['seo_default_description'] ?? '')"><meta property="og:url" content="{{ url()->current() }}">@hasSection('og_image')<meta property="og:image" content="@yield('og_image')">@endif
<link rel="preload" href="{{ asset('fonts/BYekan.woff2') }}" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="{{ asset('assets/css/app.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/storefront-extras.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/navigation-luxury.css') }}">@stack('head')
</head>
<body class="@yield('body_class')">
<a class="skip-link" href="#main">رفتن به محتوای اصلی</a>
<div class="utility-bar"><div class="container utility-inner"><div class="utility-contact">@if(!empty($settings['store_phone']))<a class="ltr" href="tel:{{ $settings['store_phone'] }}">☎ {{ $settings['store_phone'] }}</a>@endif<span>ارسال تخصصی و بیمه‌شده</span></div><div class="utility-links"><a href="{{ route('pages.faq') }}">راهنمای خرید</a><a href="{{ route('pages.contact') }}">پشتیبانی</a><a href="{{ route('wishlist.index') }}">علاقه‌مندی‌ها ♡</a></div></div></div>
<header class="site-header luxury-header" data-header>
    <div class="container header-row">
        <a class="brand" href="{{ route('home') }}" aria-label="صفحه اصلی {{ $settings['store_name'] ?? 'خانه فرش' }}"><span class="brand-mark" aria-hidden="true">◈</span><span><b>{{ $settings['store_name'] ?? 'خانه فرش' }}</b><small>{{ $settings['store_tagline'] ?? 'CARPET HOUSE' }}</small></span></a>
        <form class="header-search" action="{{ route('catalog.index') }}" method="get"><span>⌕</span><input type="search" name="q" placeholder="جستجوی فرش، طرح، رنگ، دسته‌بندی..." value="{{ request('q') }}" aria-label="جستجوی محصولات"></form>
        <div class="header-actions"><a class="icon-btn cart-button" href="{{ route('wishlist.index') }}" aria-label="علاقه‌مندی‌ها">♡<span>{{ count(session('wishlist',[])) }}</span></a><a class="icon-btn cart-button" href="{{ route('compare.index') }}" aria-label="مقایسه">⇄<span>{{ count(session('compare',[])) }}</span></a><a class="icon-btn cart-button" href="{{ route('cart.index') }}" aria-label="سبد خرید">▢<span>{{ collect(session('cart',[]))->sum('quantity') }}</span></a><button class="menu-toggle" type="button" data-menu-toggle aria-label="باز کردن منو" aria-expanded="false">☰</button></div>
    </div>
    <div class="primary-nav-wrap"><nav class="container primary-nav" aria-label="منوی اصلی">
        <a href="{{ route('home') }}">صفحه اصلی</a>
        <div class="nav-mega"><a href="{{ route('catalog.index') }}">فرش‌ها <span>⌄</span></a><div class="mega-panel"><div class="mega-copy"><span class="eyebrow">CURATED CARPETS</span><strong>همه فرش‌ها، یک‌جا و بر اساس سبک و کاربرد</strong><p>از قالی دستباف تا فرش ماشینی، گلیم، رانر و موکت؛ برای هر فضا یک انتخاب دقیق.</p><a class="mega-cta" href="{{ route('catalog.index') }}">مشاهده همه محصولات ←</a></div><div class="mega-category-columns"><div><strong>دسته‌بندی اصلی</strong><a href="{{ route('catalog.index',['category'=>'handmade']) }}">قالی دستباف</a><a href="{{ route('catalog.index',['category'=>'machine-made']) }}">فرش ماشینی</a><a href="{{ route('catalog.index',['category'=>'wall-rug']) }}">تابلو فرش</a><a href="{{ route('catalog.index',['category'=>'rug']) }}">قالیچه و فرشینه</a></div><div><strong>کف‌پوش و بافت</strong><a href="{{ route('catalog.index',['category'=>'moquette']) }}">موکت</a><a href="{{ route('catalog.index',['category'=>'carpet-tile']) }}">موکت‌تایل و موکت‌فرش</a><a href="{{ route('catalog.index',['category'=>'runner']) }}">کناره و رانر</a><a href="{{ route('catalog.index',['category'=>'kilim']) }}">گلیم و بافت تخت</a></div><div><strong>بر اساس نیاز</strong><a href="{{ route('home') }}#room-selector">دیدن فرش در اتاق</a><a href="{{ route('pages.custom-order') }}">سفارش اختصاصی</a><a href="{{ route('pages.services') }}">مشاوره پروژه</a><a href="{{ route('projects.index') }}">پروژه‌های اجراشده</a></div></div><div class="mega-feature-card"><img src="{{ asset('assets/img/hero-room.svg') }}" alt="کالکشن روشن" loading="lazy"><small>پیشنهاد ویژه</small><b>کالکشن روشن و معاصر</b></div></div></div>
        <a href="{{ route('catalog.index',['category'=>'handmade']) }}">دستباف</a><a href="{{ route('catalog.index',['category'=>'machine-made']) }}">ماشینی</a><a href="{{ route('catalog.index',['category'=>'wall-rug']) }}">تابلوفرش</a><a href="{{ route('catalog.index',['category'=>'moquette']) }}">موکت و تایل</a><a href="{{ route('catalog.index',['category'=>'kilim']) }}">گلیم و رانر</a><a href="{{ route('projects.index') }}">پروژه‌ها</a><a href="{{ route('pages.custom-order') }}">سفارش اختصاصی</a><a href="{{ route('pages.services') }}">خدمات</a><a href="{{ route('home') }}#magazine">مجله</a><a href="{{ route('pages.about') }}">درباره ما</a><a href="{{ route('pages.contact') }}">تماس با ما</a>
    </nav></div>
    <div class="mobile-expanded-menu mobile-menu"><a href="{{ route('catalog.index') }}">فروشگاه</a><a href="{{ route('pages.custom-order') }}">سفارش اختصاصی</a><a href="{{ route('projects.index') }}">پروژه‌ها</a><a href="{{ route('pages.services') }}">خدمات</a><a href="{{ route('pages.faq') }}">سوالات متداول</a><a href="{{ route('pages.about') }}">درباره ما</a><a href="{{ route('pages.contact') }}">تماس با ما</a></div>
</header>
@if(session('success'))<div class="toast" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="toast toast-error" role="alert">{{ $errors->first() }}</div>@endif
<main id="main">@yield('content')</main>
<footer class="site-footer large-footer">
<div class="container">
    <div class="footer-newsletter"><div><h3>برای انتخاب فرش مردد هستید؟</h3><p>ابعاد و سبک فضای خود را بفرستید تا چند گزینه مناسب پیشنهاد شود.</p></div><div class="admin-actions"><a class="btn btn-primary" href="{{ route('pages.custom-order') }}">ثبت سفارش و مشاوره</a><a class="btn btn-ghost" href="{{ route('pages.contact') }}">تماس با ما</a></div></div>
    <div class="footer-mega-grid">
        <div class="footer-brand-large"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">◈</span><span><b>{{ $settings['store_name'] ?? 'خانه فرش' }}</b><small>{{ $settings['store_tagline'] ?? 'CARPET HOUSE' }}</small></span></a><p>مرجع تخصصی انتخاب و خرید قالی، فرش، تابلوفرش، موکت، گلیم و محصولات پروژه‌ای با رویکرد روشن، دقیق و معمارانه.</p>@if(!empty($settings['store_phone']))<a class="ltr" href="tel:{{ $settings['store_phone'] }}">{{ $settings['store_phone'] }}</a>@endif @if(!empty($settings['store_address']))<p>{{ $settings['store_address'] }}</p>@endif<div class="footer-social">@if(!empty($settings['instagram_url']))<a href="{{ $settings['instagram_url'] }}" target="_blank" rel="noopener">◎</a>@endif<a href="{{ route('pages.contact') }}">✉</a><a href="{{ route('projects.index') }}">◇</a></div></div>
        <div class="footer-column"><strong>دسترسی سریع</strong><a href="{{ route('home') }}">صفحه اصلی</a><a href="{{ route('pages.about') }}">درباره ما</a><a href="{{ route('projects.index') }}">پروژه‌ها</a><a href="{{ route('home') }}#magazine">مجله و راهنما</a><a href="{{ route('pages.contact') }}">تماس با ما</a><a href="{{ route('sitemap') }}">نقشه سایت</a></div>
        <div class="footer-column"><strong>دسته‌بندی محصولات</strong><a href="{{ route('catalog.index',['category'=>'handmade']) }}">قالی دستباف</a><a href="{{ route('catalog.index',['category'=>'machine-made']) }}">فرش ماشینی</a><a href="{{ route('catalog.index',['category'=>'wall-rug']) }}">تابلوفرش</a><a href="{{ route('catalog.index',['category'=>'moquette']) }}">موکت</a><a href="{{ route('catalog.index',['category'=>'runner']) }}">کناره و رانر</a><a href="{{ route('catalog.index',['category'=>'kilim']) }}">گلیم</a></div>
        <div class="footer-column"><strong>خدمات مشتریان</strong><a href="{{ route('pages.custom-order') }}">سفارش اختصاصی</a><a href="{{ route('pages.services') }}">مشاوره تخصصی</a><a href="{{ route('pages.faq') }}">سوالات متداول</a><a href="{{ route('cart.index') }}">سبد خرید</a><a href="{{ route('wishlist.index') }}">علاقه‌مندی‌ها</a><a href="{{ route('compare.index') }}">مقایسه محصولات</a></div>
        <div class="footer-column"><strong>خرید مطمئن</strong><span>پرداخت امن زرین‌پال</span><span>ضمانت اصالت و کیفیت</span><span>ارسال تخصصی و بیمه‌شده</span><span>پیگیری سفارش و فاکتور</span><div class="footer-trust"><span>ZARINPAL</span><span>SSL</span><span>MEDIA LIBRARY</span></div></div>
    </div>
    <div class="footer-bottom luxury-footer-bottom"><span>© {{ now()->year }} {{ $settings['store_name'] ?? 'خانه فرش' }} — تمامی حقوق محفوظ است.</span><span class="footer-credit">ساخته شده توسط <a href="https://redcoweb.ir" target="_blank" rel="noopener">redcoweb.ir</a></span><span class="footer-legal"><a href="{{ route('pages.faq') }}">قوانین و راهنما</a><a href="{{ route('pages.contact') }}">پشتیبانی</a></span></div>
</div>
</footer>
<script src="{{ asset('assets/js/app.js') }}" defer></script>@stack('scripts')@stack('structured-data')
</body></html>
