@extends('layouts.admin')
@section('title',($category->exists?'ویرایش دسته':'دسته جدید').' | مدیریت')
@section('content')
<div class="admin-top"><h1>{{ $category->exists?'ویرایش دسته':'دسته جدید' }}</h1><a class="admin-btn alt" href="{{ route('admin.categories.index') }}">بازگشت</a></div>
<form class="admin-grid" method="post" enctype="multipart/form-data" action="{{ $category->exists?route('admin.categories.update',$category):route('admin.categories.store') }}">@csrf @if($category->exists)@method('PUT')@endif
<div class="admin-card admin-grid admin-grid-2"><div class="admin-field"><label>نام</label><input name="name" required value="{{ old('name',$category->name) }}"></div><div class="admin-field"><label>Slug</label><input class="ltr" name="slug" value="{{ old('slug',$category->slug) }}"></div><div class="admin-field"><label>والد</label><select name="parent_id"><option value="">بدون والد</option>@foreach($parents as $p)<option value="{{ $p->id }}" @selected((string)old('parent_id',$category->parent_id)===(string)$p->id)>{{ $p->name }}</option>@endforeach</select></div><div class="admin-field"><label>ترتیب</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$category->sort_order??0) }}"></div><div class="admin-field" style="grid-column:1/-1"><label>توضیحات</label><textarea rows="5" name="description">{{ old('description',$category->description) }}</textarea></div><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$category->exists?$category->is_active:true))> فعال</label></div>
<div class="admin-card"><h3>کاور دسته — Media Library</h3><div class="admin-field"><input type="file" name="cover" accept="image/jpeg,image/png,image/webp"></div>@if($category->exists && $category->getFirstMedia('cover'))<div style="margin-top:12px"><img class="thumb" src="{{ $category->cover_url }}" alt=""><label><input type="checkbox" name="remove_cover" value="1"> حذف کاور فعلی</label></div>@endif</div>
<button class="admin-btn gold">ذخیره</button></form>
@endsection
